#-------------------------------------------------
#
# Project created by QtCreator 2015-06-09T16:22:45
#
#-------------------------------------------------

QT       += core
QT       -= gui

TARGET = BasicSystem
CONFIG   += console
CONFIG   -= app_bundle

TEMPLATE = app

DEFINES +=  \

INCLUDEPATH +=  \
    Driver/Include/ \
    Library/SmartcardLib/Include/ \
    Library/UsbHostLib/inc/ \
    Library/UsbHostLib/src_msc/ \
    ThirdParty/FATFS/src/ \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/\
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/\
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/RVDS/ARM9_NUC970/ \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/ \
    ThirdParty/lwip-1.4.1/src/include/lwip/\
    ThirdParty/lwip-1.4.1/src/include/netif/ \
    ThirdParty/lwip-1.4.1/src/include/posix/sys/ \
    ThirdParty/lwip-1.4.1/src/include/posix/\
    ThirdParty/lwip-1.4.1/src/netif/ppp/\
    ThirdParty/lwip-1.4.1/test/unit/core/ \
    ThirdParty/lwip-1.4.1/test/unit/etharp/\
    ThirdParty/lwip-1.4.1/test/unit/tcp/ \
    ThirdParty/lwip-1.4.1/test/unit/udp/ \
    ThirdParty/lwip-1.4.1/test/unit/ \
    ThirdParty/yaffs2/include/asm/ \
    ThirdParty/yaffs2/include/linux/ \
    ThirdParty/yaffs2/include/\
    ThirdParty/yaffs2/ \
    User/   \
    User/lvgl/lv_core/ \
    User/lvgl/lv_draw/ \
    User/lvgl/lv_fonts/ \
    User/lvgl/lv_hal/ \
    User/lvgl/lv_misc/ \
    User/lvgl/lv_objx/ \
    User/lvgl/lv_themes/ \
    User/lvgl/  \
    User/LCD/   \
    User/ui/

HEADERS += \
    Driver/Include/2d.h \
    Driver/Include/adc.h \
    Driver/Include/can.h \
    Driver/Include/cap.h \
    Driver/Include/crypto.h \
    Driver/Include/etimer.h \
    Driver/Include/fmi.h \
    Driver/Include/gpio.h \
    Driver/Include/i2c.h \
    Driver/Include/i2s.h \
    Driver/Include/jpeg.h \
    Driver/Include/jpegcodec.h \
    Driver/Include/kpi.h \
    Driver/Include/lcd.h \
    Driver/Include/mtp.h \
    Driver/Include/nuc970.h \
    Driver/Include/pwm.h \
    Driver/Include/rtc.h \
    Driver/Include/sc.h \
    Driver/Include/scuart.h \
    Driver/Include/sdh.h \
    Driver/Include/spi.h \
    Driver/Include/sys.h \
    Driver/Include/uart.h \
    Driver/Include/usbd.h \
    Driver/Include/wwdt.h \
    Library/SmartcardLib/Include/sclib.h \
    Library/UsbHostLib/inc/config.h \
    Library/UsbHostLib/inc/ehci.h \
    Library/UsbHostLib/inc/hub.h \
    Library/UsbHostLib/inc/ohci.h \
    Library/UsbHostLib/inc/usb.h \
    Library/UsbHostLib/inc/usbh_hid.h \
    Library/UsbHostLib/inc/usbh_lib.h \
    Library/UsbHostLib/inc/usbh_uac.h \
    Library/UsbHostLib/inc/usbh_uvc.h \
    Library/UsbHostLib/src_msc/msc.h \
    Library/UsbHostLib/src_uac/uac.h \
    ThirdParty/FATFS/src/diskio.h \
    ThirdParty/FATFS/src/ff.h \
    ThirdParty/FATFS/src/ffconf.h \
    ThirdParty/FATFS/src/integer.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/AbortDelay.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/BlockQ.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/blocktim.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/comtest.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/comtest2.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/comtest_strings.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/countsem.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/crflash.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/crhook.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/death.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/dynamic.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/EventGroupsDemo.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/fileIO.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/flash.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/flash_timer.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/flop.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/GenQTest.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/integer.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/IntQueue.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/IntSemTest.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/mevents.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/partest.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/PollQ.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/print.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/QPeek.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/QueueOverwrite.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/QueueSet.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/QueueSetPolling.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/recmutex.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/semtest.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/serial.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/StaticAllocation.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/TaskNotify.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/include/TimerDemo.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/croutine.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/deprecated_definitions.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/event_groups.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/FreeRTOS.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/list.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/mpu_prototypes.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/mpu_wrappers.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/portable.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/projdefs.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/queue.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/semphr.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/StackMacros.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/task.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/include/timers.h \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/RVDS/ARM9_NUC970/portmacro.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/autoip.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/icmp.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/igmp.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/inet.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/inet_chksum.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/ip.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/ip_addr.h \
    ThirdParty/lwip-1.4.1/src/include/ipv4/lwip/ip_frag.h \
    ThirdParty/lwip-1.4.1/src/include/ipv6/lwip/icmp.h \
    ThirdParty/lwip-1.4.1/src/include/ipv6/lwip/inet.h \
    ThirdParty/lwip-1.4.1/src/include/ipv6/lwip/ip.h \
    ThirdParty/lwip-1.4.1/src/include/ipv6/lwip/ip_addr.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/api.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/api_msg.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/arch.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/debug.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/def.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/dhcp.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/dns.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/err.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/init.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/mem.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/memp.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/memp_std.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/netbuf.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/netdb.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/netif.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/netifapi.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/opt.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/pbuf.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/raw.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/sio.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/snmp.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/snmp_asn1.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/snmp_msg.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/snmp_structs.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/sockets.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/stats.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/sys.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/tcp.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/tcp_impl.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/tcpip.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/timers.h \
    ThirdParty/lwip-1.4.1/src/include/lwip/udp.h \
    ThirdParty/lwip-1.4.1/src/include/netif/etharp.h \
    ThirdParty/lwip-1.4.1/src/include/netif/ppp_oe.h \
    ThirdParty/lwip-1.4.1/src/include/netif/slipif.h \
    ThirdParty/lwip-1.4.1/src/include/posix/sys/socket.h \
    ThirdParty/lwip-1.4.1/src/include/posix/netdb.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/auth.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/chap.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/chpms.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/fsm.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/ipcp.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/lcp.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/magic.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/md5.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/pap.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/ppp.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/ppp_impl.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/pppdebug.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/randm.h \
    ThirdParty/lwip-1.4.1/src/netif/ppp/vj.h \
    ThirdParty/lwip-1.4.1/test/unit/core/test_mem.h \
    ThirdParty/lwip-1.4.1/test/unit/etharp/test_etharp.h \
    ThirdParty/lwip-1.4.1/test/unit/tcp/tcp_helper.h \
    ThirdParty/lwip-1.4.1/test/unit/tcp/test_tcp.h \
    ThirdParty/lwip-1.4.1/test/unit/tcp/test_tcp_oos.h \
    ThirdParty/lwip-1.4.1/test/unit/udp/test_udp.h \
    ThirdParty/lwip-1.4.1/test/unit/lwip_check.h \
    ThirdParty/lwip-1.4.1/test/unit/lwipopts.h \
    ThirdParty/yaffs2/include/asm/armv7.h \
    ThirdParty/yaffs2/include/asm/assembler.h \
    ThirdParty/yaffs2/include/asm/atomic.h \
    ThirdParty/yaffs2/include/asm/bitops.h \
    ThirdParty/yaffs2/include/asm/bootm.h \
    ThirdParty/yaffs2/include/asm/byteorder.h \
    ThirdParty/yaffs2/include/asm/cache.h \
    ThirdParty/yaffs2/include/asm/config.h \
    ThirdParty/yaffs2/include/asm/dma-mapping.h \
    ThirdParty/yaffs2/include/asm/ehci-omap.h \
    ThirdParty/yaffs2/include/asm/emif.h \
    ThirdParty/yaffs2/include/asm/errno.h \
    ThirdParty/yaffs2/include/asm/global_data.h \
    ThirdParty/yaffs2/include/asm/gpio.h \
    ThirdParty/yaffs2/include/asm/hardware.h \
    ThirdParty/yaffs2/include/asm/io.h \
    ThirdParty/yaffs2/include/asm/linkage.h \
    ThirdParty/yaffs2/include/asm/mach-types.h \
    ThirdParty/yaffs2/include/asm/macro.h \
    ThirdParty/yaffs2/include/asm/memory.h \
    ThirdParty/yaffs2/include/asm/omap_common.h \
    ThirdParty/yaffs2/include/asm/omap_gpio.h \
    ThirdParty/yaffs2/include/asm/omap_mmc.h \
    ThirdParty/yaffs2/include/asm/omap_musb.h \
    ThirdParty/yaffs2/include/asm/pl310.h \
    ThirdParty/yaffs2/include/asm/posix_types.h \
    ThirdParty/yaffs2/include/asm/processor.h \
    ThirdParty/yaffs2/include/asm/ptrace.h \
    ThirdParty/yaffs2/include/asm/sections.h \
    ThirdParty/yaffs2/include/asm/setup.h \
    ThirdParty/yaffs2/include/asm/sizes.h \
    ThirdParty/yaffs2/include/asm/spl.h \
    ThirdParty/yaffs2/include/asm/string.h \
    ThirdParty/yaffs2/include/asm/system.h \
    ThirdParty/yaffs2/include/asm/types.h \
    ThirdParty/yaffs2/include/asm/u-boot-arm.h \
    ThirdParty/yaffs2/include/asm/u-boot.h \
    ThirdParty/yaffs2/include/asm/unaligned.h \
    ThirdParty/yaffs2/include/asm/utils.h \
    ThirdParty/yaffs2/include/linux/apm_bios.h \
    ThirdParty/yaffs2/include/linux/bbm.h \
    ThirdParty/yaffs2/include/linux/bch.h \
    ThirdParty/yaffs2/include/linux/bitops.h \
    ThirdParty/yaffs2/include/linux/compat.h \
    ThirdParty/yaffs2/include/linux/compiler-gcc.h \
    ThirdParty/yaffs2/include/linux/compiler-gcc3.h \
    ThirdParty/yaffs2/include/linux/compiler-gcc4.h \
    ThirdParty/yaffs2/include/linux/compiler.h \
    ThirdParty/yaffs2/include/linux/config.h \
    ThirdParty/yaffs2/include/linux/crc32.h \
    ThirdParty/yaffs2/include/linux/crc7.h \
    ThirdParty/yaffs2/include/linux/ctype.h \
    ThirdParty/yaffs2/include/linux/edd.h \
    ThirdParty/yaffs2/include/linux/err.h \
    ThirdParty/yaffs2/include/linux/ethtool.h \
    ThirdParty/yaffs2/include/linux/fb.h \
    ThirdParty/yaffs2/include/linux/input.h \
    ThirdParty/yaffs2/include/linux/ioctl.h \
    ThirdParty/yaffs2/include/linux/ioport.h \
    ThirdParty/yaffs2/include/linux/kbuild.h \
    ThirdParty/yaffs2/include/linux/linkage.h \
    ThirdParty/yaffs2/include/linux/linux_string.h \
    ThirdParty/yaffs2/include/linux/list.h \
    ThirdParty/yaffs2/include/linux/little_endian.h \
    ThirdParty/yaffs2/include/linux/lzo.h \
    ThirdParty/yaffs2/include/linux/math64.h \
    ThirdParty/yaffs2/include/linux/mc146818rtc.h \
    ThirdParty/yaffs2/include/linux/mdio.h \
    ThirdParty/yaffs2/include/linux/mii.h \
    ThirdParty/yaffs2/include/linux/mtd-abi.h \
    ThirdParty/yaffs2/include/linux/mtd.h \
    ThirdParty/yaffs2/include/linux/nand.h \
    ThirdParty/yaffs2/include/linux/nand_bch.h \
    ThirdParty/yaffs2/include/linux/nand_ecc.h \
    ThirdParty/yaffs2/include/linux/netdevice.h \
    ThirdParty/yaffs2/include/linux/partitions.h \
    ThirdParty/yaffs2/include/linux/poison.h \
    ThirdParty/yaffs2/include/linux/posix_types.h \
    ThirdParty/yaffs2/include/linux/rbtree.h \
    ThirdParty/yaffs2/include/linux/screen_info.h \
    ThirdParty/yaffs2/include/linux/stat.h \
    ThirdParty/yaffs2/include/linux/stddef.h \
    ThirdParty/yaffs2/include/linux/string.h \
    ThirdParty/yaffs2/include/linux/stringify.h \
    ThirdParty/yaffs2/include/linux/swab.h \
    ThirdParty/yaffs2/include/linux/time.h \
    ThirdParty/yaffs2/include/linux/types.h \
    ThirdParty/yaffs2/include/bootstage.h \
    ThirdParty/yaffs2/include/command.h \
    ThirdParty/yaffs2/include/common.h \
    ThirdParty/yaffs2/include/compiler.h \
    ThirdParty/yaffs2/include/config.h \
    ThirdParty/yaffs2/include/crc.h \
    ThirdParty/yaffs2/include/div64.h \
    ThirdParty/yaffs2/include/flash.h \
    ThirdParty/yaffs2/include/global_data.h \
    ThirdParty/yaffs2/include/ide.h \
    ThirdParty/yaffs2/include/image.h \
    ThirdParty/yaffs2/include/linker_lists.h \
    ThirdParty/yaffs2/include/lmb.h \
    ThirdParty/yaffs2/include/malloc.h \
    ThirdParty/yaffs2/include/nand.h \
    ThirdParty/yaffs2/include/part.h \
    ThirdParty/yaffs2/include/vsprintf.h \
    ThirdParty/yaffs2/yaffs_allocator.h \
    ThirdParty/yaffs2/yaffs_attribs.h \
    ThirdParty/yaffs2/yaffs_bitmap.h \
    ThirdParty/yaffs2/yaffs_checkptrw.h \
    ThirdParty/yaffs2/yaffs_ecc.h \
    ThirdParty/yaffs2/yaffs_flashif.h \
    ThirdParty/yaffs2/yaffs_flashif2.h \
    ThirdParty/yaffs2/yaffs_getblockinfo.h \
    ThirdParty/yaffs2/yaffs_guts.h \
    ThirdParty/yaffs2/yaffs_list.h \
    ThirdParty/yaffs2/yaffs_malloc.h \
    ThirdParty/yaffs2/yaffs_mtdif.h \
    ThirdParty/yaffs2/yaffs_mtdif2.h \
    ThirdParty/yaffs2/yaffs_nameval.h \
    ThirdParty/yaffs2/yaffs_nand.h \
    ThirdParty/yaffs2/yaffs_nandemul2k.h \
    ThirdParty/yaffs2/yaffs_nandif.h \
    ThirdParty/yaffs2/yaffs_osglue.h \
    ThirdParty/yaffs2/yaffs_packedtags1.h \
    ThirdParty/yaffs2/yaffs_packedtags2.h \
    ThirdParty/yaffs2/yaffs_summary.h \
    ThirdParty/yaffs2/yaffs_tagscompat.h \
    ThirdParty/yaffs2/yaffs_trace.h \
    ThirdParty/yaffs2/yaffs_verify.h \
    ThirdParty/yaffs2/yaffs_yaffs1.h \
    ThirdParty/yaffs2/yaffs_yaffs2.h \
    ThirdParty/yaffs2/yaffscfg.h \
    ThirdParty/yaffs2/yaffsfs.h \
    ThirdParty/yaffs2/ydirectenv.h \
    ThirdParty/yaffs2/yportenv.h \
    User/LCD/LCD.h \
    User/LCD/lcd_bsp.h \
    User/lvgl/lv_core/lv_group.h \
    User/lvgl/lv_core/lv_indev.h \
    User/lvgl/lv_core/lv_obj.h \
    User/lvgl/lv_core/lv_refr.h \
    User/lvgl/lv_core/lv_style.h \
    User/lvgl/lv_core/lv_vdb.h \
    User/lvgl/lv_draw/lv_draw.h \
    User/lvgl/lv_draw/lv_draw_arc.h \
    User/lvgl/lv_draw/lv_draw_img.h \
    User/lvgl/lv_draw/lv_draw_label.h \
    User/lvgl/lv_draw/lv_draw_line.h \
    User/lvgl/lv_draw/lv_draw_rbasic.h \
    User/lvgl/lv_draw/lv_draw_rect.h \
    User/lvgl/lv_draw/lv_draw_triangle.h \
    User/lvgl/lv_draw/lv_draw_vbasic.h \
    User/lvgl/lv_fonts/lv_font_builtin.h \
    User/lvgl/lv_hal/lv_hal.h \
    User/lvgl/lv_hal/lv_hal_disp.h \
    User/lvgl/lv_hal/lv_hal_indev.h \
    User/lvgl/lv_hal/lv_hal_tick.h \
    User/lvgl/lv_misc/lv_anim.h \
    User/lvgl/lv_misc/lv_area.h \
    User/lvgl/lv_misc/lv_circ.h \
    User/lvgl/lv_misc/lv_color.h \
    User/lvgl/lv_misc/lv_font.h \
    User/lvgl/lv_misc/lv_fs.h \
    User/lvgl/lv_misc/lv_ll.h \
    User/lvgl/lv_misc/lv_log.h \
    User/lvgl/lv_misc/lv_math.h \
    User/lvgl/lv_misc/lv_mem.h \
    User/lvgl/lv_misc/lv_symbol_def.h \
    User/lvgl/lv_misc/lv_task.h \
    User/lvgl/lv_misc/lv_templ.h \
    User/lvgl/lv_misc/lv_txt.h \
    User/lvgl/lv_misc/lv_ufs.h \
    User/lvgl/lv_objx/lv_arc.h \
    User/lvgl/lv_objx/lv_bar.h \
    User/lvgl/lv_objx/lv_btn.h \
    User/lvgl/lv_objx/lv_btnm.h \
    User/lvgl/lv_objx/lv_calendar.h \
    User/lvgl/lv_objx/lv_cb.h \
    User/lvgl/lv_objx/lv_chart.h \
    User/lvgl/lv_objx/lv_cont.h \
    User/lvgl/lv_objx/lv_ddlist.h \
    User/lvgl/lv_objx/lv_gauge.h \
    User/lvgl/lv_objx/lv_img.h \
    User/lvgl/lv_objx/lv_imgbtn.h \
    User/lvgl/lv_objx/lv_kb.h \
    User/lvgl/lv_objx/lv_label.h \
    User/lvgl/lv_objx/lv_led.h \
    User/lvgl/lv_objx/lv_line.h \
    User/lvgl/lv_objx/lv_list.h \
    User/lvgl/lv_objx/lv_lmeter.h \
    User/lvgl/lv_objx/lv_mbox.h \
    User/lvgl/lv_objx/lv_objx_templ.h \
    User/lvgl/lv_objx/lv_page.h \
    User/lvgl/lv_objx/lv_preload.h \
    User/lvgl/lv_objx/lv_roller.h \
    User/lvgl/lv_objx/lv_slider.h \
    User/lvgl/lv_objx/lv_sw.h \
    User/lvgl/lv_objx/lv_ta.h \
    User/lvgl/lv_objx/lv_tabview.h \
    User/lvgl/lv_objx/lv_win.h \
    User/lvgl/lv_themes/lv_theme.h \
    User/lvgl/lv_themes/lv_theme_alien.h \
    User/lvgl/lv_themes/lv_theme_default.h \
    User/lvgl/lv_themes/lv_theme_material.h \
    User/lvgl/lv_themes/lv_theme_mono.h \
    User/lvgl/lv_themes/lv_theme_nemo.h \
    User/lvgl/lv_themes/lv_theme_night.h \
    User/lvgl/lv_themes/lv_theme_templ.h \
    User/lvgl/lv_themes/lv_theme_zen.h \
    User/lvgl/lv_conf_templ.h \
    User/lvgl/lvgl.h \
    User/ui/desktop.h \
    User/lv_conf.h

SOURCES += \
    Driver/Source/2d.c \
    Driver/Source/adc.c \
    Driver/Source/can.c \
    Driver/Source/cap.c \
    Driver/Source/crypto.c \
    Driver/Source/etimer.c \
    Driver/Source/fmi.c \
    Driver/Source/gpio.c \
    Driver/Source/i2c.c \
    Driver/Source/i2s.c \
    Driver/Source/jpegcodec.c \
    Driver/Source/kpi.c \
    Driver/Source/lcd.c \
    Driver/Source/mtp.c \
    Driver/Source/pwm.c \
    Driver/Source/rtc.c \
    Driver/Source/sc.c \
    Driver/Source/scuart.c \
    Driver/Source/sdh.c \
    Driver/Source/spi.c \
    Driver/Source/standalone.c \
    Driver/Source/sys.c \
    Driver/Source/sys_ebi.c \
    Driver/Source/sys_timer.c \
    Driver/Source/sys_uart.c \
    Driver/Source/system_nuc970.c \
    Driver/Source/uart.c \
    Driver/Source/usbd.c \
    Driver/Source/wwdt.c \
    Library/UsbHostLib/src_core/ehci.c \
    Library/UsbHostLib/src_core/ehci_iso.c \
    Library/UsbHostLib/src_core/hub.c \
    Library/UsbHostLib/src_core/mem_alloc.c \
    Library/UsbHostLib/src_core/ohci.c \
    Library/UsbHostLib/src_core/support.c \
    Library/UsbHostLib/src_core/usb_core.c \
    Library/UsbHostLib/src_hid/hid_core.c \
    Library/UsbHostLib/src_hid/hid_driver.c \
    Library/UsbHostLib/src_msc/msc_driver.c \
    Library/UsbHostLib/src_msc/msc_xfer.c \
    Library/UsbHostLib/src_uac/uac_core.c \
    Library/UsbHostLib/src_uac/uac_driver.c \
    Library/UsbHostLib/src_uac/uac_parser.c \
    Library/UsbHostLib/src_uvc/uvc_core.c \
    Library/UsbHostLib/src_uvc/uvc_driver.c \
    Library/UsbHostLib/src_uvc/uvc_parser.c \
    ThirdParty/FATFS/src/option/cc932.c \
    ThirdParty/FATFS/src/option/cc936.c \
    ThirdParty/FATFS/src/option/cc949.c \
    ThirdParty/FATFS/src/option/cc950.c \
    ThirdParty/FATFS/src/option/ccsbcs.c \
    ThirdParty/FATFS/src/option/syscall.c \
    ThirdParty/FATFS/src/option/unicode.c \
    ThirdParty/FATFS/src/diskio.c \
    ThirdParty/FATFS/src/ff.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/BlockQ.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/comtest.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/death.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/dynamic.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/events.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/flash.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/flop.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/integer.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/PollQ.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/print.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Full/semtest.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/AbortDelay.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/BlockQ.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/blocktim.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/comtest.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/comtest_strings.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/countsem.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/crflash.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/crhook.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/death.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/dynamic.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/EventGroupsDemo.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/flash.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/flash_timer.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/flop.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/GenQTest.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/integer.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/IntQueue.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/IntSemTest.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/PollQ.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/QPeek.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/QueueOverwrite.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/QueueSet.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/QueueSetPolling.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/recmutex.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/semtest.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/sp_flop.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/StaticAllocation.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/TaskNotify.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Demo/Common/Minimal/TimerDemo.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/MemMang/heap_1.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/MemMang/heap_2.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/MemMang/heap_3.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/MemMang/heap_4.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/MemMang/heap_5.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/portable/RVDS/ARM9_NUC970/port.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/croutine.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/event_groups.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/list.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/queue.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/tasks.c \
    ThirdParty/FreeRTOSV9.0.0/FreeRTOS/Source/timers.c \
    ThirdParty/lwip-1.4.1/src/api/api_lib.c \
    ThirdParty/lwip-1.4.1/src/api/api_msg.c \
    ThirdParty/lwip-1.4.1/src/api/err.c \
    ThirdParty/lwip-1.4.1/src/api/netbuf.c \
    ThirdParty/lwip-1.4.1/src/api/netdb.c \
    ThirdParty/lwip-1.4.1/src/api/netifapi.c \
    ThirdParty/lwip-1.4.1/src/api/sockets.c \
    ThirdParty/lwip-1.4.1/src/api/tcpip.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/autoip.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/icmp.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/igmp.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/inet.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/inet_chksum.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/ip.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/ip_addr.c \
    ThirdParty/lwip-1.4.1/src/core/ipv4/ip_frag.c \
    ThirdParty/lwip-1.4.1/src/core/ipv6/icmp6.c \
    ThirdParty/lwip-1.4.1/src/core/ipv6/inet6.c \
    ThirdParty/lwip-1.4.1/src/core/ipv6/ip6.c \
    ThirdParty/lwip-1.4.1/src/core/ipv6/ip6_addr.c \
    ThirdParty/lwip-1.4.1/src/core/snmp/asn1_dec.c \
    ThirdParty/lwip-1.4.1/src/core/snmp/asn1_enc.c \
    ThirdParty/lwip-1.4.1/src/core/snmp/mib2.c \
    ThirdParty/lwip-1.4.1/src/core/snmp/mib_structs.c \
    ThirdParty/lwip-1.4.1/src/core/snmp/msg_in.c \
    ThirdParty/lwip-1.4.1/src/core/snmp/msg_out.c \
    ThirdParty/lwip-1.4.1/src/core/def.c \
    ThirdParty/lwip-1.4.1/src/core/dhcp.c \
    ThirdParty/lwip-1.4.1/src/core/dns.c \
    ThirdParty/lwip-1.4.1/src/core/init.c \
    ThirdParty/lwip-1.4.1/src/core/mem.c \
    ThirdParty/lwip-1.4.1/src/core/memp.c \
    ThirdParty/lwip-1.4.1/src/core/netif.c \
    ThirdParty/lwip-1.4.1/src/core/pbuf.c \
    ThirdParty/lwip-1.4.1/src/core/raw.c \
    ThirdParty/lwip-1.4.1/src/core/stats.c \
    ThirdParty/lwip-1.4.1/src/core/sys.c \
    ThirdParty/lwip-1.4.1/src/core/tcp.c \
    ThirdParty/lwip-1.4.1/src/core/tcp_in.c \
    ThirdParty/lwip-1.4.1/src/core/tcp_out.c \
    ThirdParty/lwip-1.4.1/src/core/timers.c \
    ThirdParty/lwip-1.4.1/src/core/udp.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/auth.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/chap.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/chpms.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/fsm.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/ipcp.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/lcp.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/magic.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/md5.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/pap.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/ppp.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/ppp_oe.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/randm.c \
    ThirdParty/lwip-1.4.1/src/netif/ppp/vj.c \
    ThirdParty/lwip-1.4.1/src/netif/etharp.c \
    ThirdParty/lwip-1.4.1/src/netif/ethernetif.c \
    ThirdParty/lwip-1.4.1/src/netif/slipif.c \
    ThirdParty/lwip-1.4.1/test/unit/core/test_mem.c \
    ThirdParty/lwip-1.4.1/test/unit/etharp/test_etharp.c \
    ThirdParty/lwip-1.4.1/test/unit/tcp/tcp_helper.c \
    ThirdParty/lwip-1.4.1/test/unit/tcp/test_tcp.c \
    ThirdParty/lwip-1.4.1/test/unit/tcp/test_tcp_oos.c \
    ThirdParty/lwip-1.4.1/test/unit/udp/test_udp.c \
    ThirdParty/lwip-1.4.1/test/unit/lwip_unittests.c \
    ThirdParty/yaffs2/platform/fmi_nand.c \
    ThirdParty/yaffs2/mtdcore.c \
    ThirdParty/yaffs2/mtdpart.c \
    ThirdParty/yaffs2/nand.c \
    ThirdParty/yaffs2/nand_base.c \
    ThirdParty/yaffs2/nand_bbt.c \
    ThirdParty/yaffs2/nand_ids.c \
    ThirdParty/yaffs2/nand_util.c \
    ThirdParty/yaffs2/yaffs_allocator.c \
    ThirdParty/yaffs2/yaffs_attribs.c \
    ThirdParty/yaffs2/yaffs_bitmap.c \
    ThirdParty/yaffs2/yaffs_checkptrw.c \
    ThirdParty/yaffs2/yaffs_ecc.c \
    ThirdParty/yaffs2/yaffs_error.c \
    ThirdParty/yaffs2/yaffs_guts.c \
    ThirdParty/yaffs2/yaffs_malloc.c \
    ThirdParty/yaffs2/yaffs_mtdif.c \
    ThirdParty/yaffs2/yaffs_mtdif2.c \
    ThirdParty/yaffs2/yaffs_nameval.c \
    ThirdParty/yaffs2/yaffs_nand.c \
    ThirdParty/yaffs2/yaffs_nandif.c \
    ThirdParty/yaffs2/yaffs_packedtags1.c \
    ThirdParty/yaffs2/yaffs_packedtags2.c \
    ThirdParty/yaffs2/yaffs_qsort.c \
    ThirdParty/yaffs2/yaffs_summary.c \
    ThirdParty/yaffs2/yaffs_tagscompat.c \
    ThirdParty/yaffs2/yaffs_verify.c \
    ThirdParty/yaffs2/yaffs_yaffs1.c \
    ThirdParty/yaffs2/yaffs_yaffs2.c \
    ThirdParty/yaffs2/yaffsfs.c \
    User/main.c \
    User/LCD/lcd_bsp.c \
    User/LCD/lcd_bsp.c \
    User/lvgl/lv_core/lv_group.c \
    User/lvgl/lv_core/lv_indev.c \
    User/lvgl/lv_core/lv_obj.c \
    User/lvgl/lv_core/lv_refr.c \
    User/lvgl/lv_core/lv_style.c \
    User/lvgl/lv_core/lv_vdb.c \
    User/lvgl/lv_draw/lv_draw.c \
    User/lvgl/lv_draw/lv_draw_arc.c \
    User/lvgl/lv_draw/lv_draw_img.c \
    User/lvgl/lv_draw/lv_draw_label.c \
    User/lvgl/lv_draw/lv_draw_line.c \
    User/lvgl/lv_draw/lv_draw_rbasic.c \
    User/lvgl/lv_draw/lv_draw_rect.c \
    User/lvgl/lv_draw/lv_draw_triangle.c \
    User/lvgl/lv_draw/lv_draw_vbasic.c \
    User/lvgl/lv_fonts/lv_font_builtin.c \
    User/lvgl/lv_fonts/lv_font_dejavu_10.c \
    User/lvgl/lv_fonts/lv_font_dejavu_10_cyrillic.c \
    User/lvgl/lv_fonts/lv_font_dejavu_10_latin_sup.c \
    User/lvgl/lv_fonts/lv_font_dejavu_20.c \
    User/lvgl/lv_fonts/lv_font_dejavu_20_cyrillic.c \
    User/lvgl/lv_fonts/lv_font_dejavu_20_latin_sup.c \
    User/lvgl/lv_fonts/lv_font_dejavu_30.c \
    User/lvgl/lv_fonts/lv_font_dejavu_30_cyrillic.c \
    User/lvgl/lv_fonts/lv_font_dejavu_30_latin_sup.c \
    User/lvgl/lv_fonts/lv_font_dejavu_40.c \
    User/lvgl/lv_fonts/lv_font_dejavu_40_cyrillic.c \
    User/lvgl/lv_fonts/lv_font_dejavu_40_latin_sup.c \
    User/lvgl/lv_fonts/lv_font_monospace_8.c \
    User/lvgl/lv_fonts/lv_font_symbol_10.c \
    User/lvgl/lv_fonts/lv_font_symbol_20.c \
    User/lvgl/lv_fonts/lv_font_symbol_30.c \
    User/lvgl/lv_fonts/lv_font_symbol_40.c \
    User/lvgl/lv_hal/lv_hal_disp.c \
    User/lvgl/lv_hal/lv_hal_indev.c \
    User/lvgl/lv_hal/lv_hal_tick.c \
    User/lvgl/lv_misc/lv_anim.c \
    User/lvgl/lv_misc/lv_area.c \
    User/lvgl/lv_misc/lv_circ.c \
    User/lvgl/lv_misc/lv_color.c \
    User/lvgl/lv_misc/lv_font.c \
    User/lvgl/lv_misc/lv_fs.c \
    User/lvgl/lv_misc/lv_ll.c \
    User/lvgl/lv_misc/lv_log.c \
    User/lvgl/lv_misc/lv_math.c \
    User/lvgl/lv_misc/lv_mem.c \
    User/lvgl/lv_misc/lv_task.c \
    User/lvgl/lv_misc/lv_templ.c \
    User/lvgl/lv_misc/lv_txt.c \
    User/lvgl/lv_misc/lv_ufs.c \
    User/lvgl/lv_objx/lv_arc.c \
    User/lvgl/lv_objx/lv_bar.c \
    User/lvgl/lv_objx/lv_btn.c \
    User/lvgl/lv_objx/lv_btnm.c \
    User/lvgl/lv_objx/lv_calendar.c \
    User/lvgl/lv_objx/lv_cb.c \
    User/lvgl/lv_objx/lv_chart.c \
    User/lvgl/lv_objx/lv_cont.c \
    User/lvgl/lv_objx/lv_ddlist.c \
    User/lvgl/lv_objx/lv_gauge.c \
    User/lvgl/lv_objx/lv_img.c \
    User/lvgl/lv_objx/lv_imgbtn.c \
    User/lvgl/lv_objx/lv_kb.c \
    User/lvgl/lv_objx/lv_label.c \
    User/lvgl/lv_objx/lv_led.c \
    User/lvgl/lv_objx/lv_line.c \
    User/lvgl/lv_objx/lv_list.c \
    User/lvgl/lv_objx/lv_lmeter.c \
    User/lvgl/lv_objx/lv_mbox.c \
    User/lvgl/lv_objx/lv_objx_templ.c \
    User/lvgl/lv_objx/lv_page.c \
    User/lvgl/lv_objx/lv_preload.c \
    User/lvgl/lv_objx/lv_roller.c \
    User/lvgl/lv_objx/lv_slider.c \
    User/lvgl/lv_objx/lv_sw.c \
    User/lvgl/lv_objx/lv_ta.c \
    User/lvgl/lv_objx/lv_tabview.c \
    User/lvgl/lv_objx/lv_win.c \
    User/lvgl/lv_themes/lv_theme.c \
    User/lvgl/lv_themes/lv_theme_alien.c \
    User/lvgl/lv_themes/lv_theme_default.c \
    User/lvgl/lv_themes/lv_theme_material.c \
    User/lvgl/lv_themes/lv_theme_mono.c \
    User/lvgl/lv_themes/lv_theme_nemo.c \
    User/lvgl/lv_themes/lv_theme_night.c \
    User/lvgl/lv_themes/lv_theme_templ.c \
    User/lvgl/lv_themes/lv_theme_zen.c \
    User/ui/desktop.c \
    User/ui/music.c



